### ISSUE TITLE
mergebot doesn't exist

### ISSUE THREAD

**Issue by jasonkuster** [jasonkuster/merge-bot#1]

**Comment by jasonkuster** [comment]
@beam-testing you should resolve this

**Comment by beam-testing** [comment]
I'll give it a shot.

On Tue, Apr 5, 2016 at 10:39 AM, jasonkuster notifications@github.com
wrote:

> @beam-testing https://github.com/beam-testing you should resolve this
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jasonkuster/merge-bot/issues/1#issuecomment-205913393

## 

---

Jason Kuster
Apache Beam (Incubating) / Google Cloud Dataflow
