### ISSUE TITLE
halp how did this get here

### ISSUE THREAD

**Issue by jasonkuster** [jasonkuster/merge-bot#3]
i am not good with computer

**Comment by beam-testing** [comment]
be better

On Tue, Apr 5, 2016 at 10:55 AM, jasonkuster notifications@github.com
wrote:

> i am not good with computer
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jasonkuster/merge-bot/issues/3

## 

---

Jason Kuster
Apache Beam (Incubating) / Google Cloud Dataflow

**Comment by beam-testing** [comment]
wheeee
